// This file is generated. Do not edit this file.
// Original file: /pipeline/pipeline.go

package middleware

import (
	"github.com/lanvard/contract/inter"
	"github.com/lanvard/support/caller"
)

type Pipe interface {
	Handle(data inter.Request, next inter.MiddlewareDestination) inter.Response
}

// noinspection GoNameStartsWithPackageName
type Pipeline struct {
	App *inter.App

	// The object being passed through the contract.
	Passable inter.Request

	// the array of pipes.
	Pipes []inter.Pipe
}

func NewPipeline(app *inter.App) Pipeline {
	return Pipeline{App: app}
}

func (p Pipeline) AppPath() string {
	return caller.Path()
}

// Set the object being sent through the contract.
func (p Pipeline) Send(passable inter.Request) Pipeline {
	p.Passable = passable

	return p
}

// Set the array of pipes.
func (p Pipeline) Through(pipes []inter.Pipe) Pipeline {
	p.Pipes = pipes

	return p
}

// Run the contract with a final destination callback.
func (p Pipeline) Then(destination inter.MiddlewareDestination) inter.Response {

	var callbacks []func(data inter.Request) inter.Response
	var nextCallback = 0

	pipes := reverse(p.Pipes)

	for i, pipe := range pipes {
		pipe := pipe
		if i == 0 {
			// Give the last callback a destination callback
			callback := func(data inter.Request) inter.Response {
				return pipe.Handle(data, destination)
			}
			callbacks = append(callbacks, callback)
		} else {
			// Give other callback the next callback
			callback := func(data inter.Request) inter.Response {
				nextCallback--
				return pipe.Handle(data, callbacks[nextCallback])
			}
			callbacks = append(callbacks, callback)
		}
	}

	nextCallback = len(callbacks) - 1

	return callbacks[nextCallback](p.Passable)
}

func reverse(pipes []inter.Pipe) []inter.Pipe {
	for left, right := 0, len(pipes)-1; left < right; left, right = left+1, right-1 {
		pipes[left], pipes[right] = pipes[right], pipes[left]
	}

	return pipes
}
